name: 'Karappo Deploy'
description: 'Deployment for Karappo Inc. using karappo/drone-deploy'
author: 'naokazuterada'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-up'
  color: 'green'
